<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '253c157292f75eb38082b5acb06f3f01' => $vendorDir . '/nikic/fast-route/src/functions.php',
    '3fc318d941c00f74bdfb6bc130765a58' => $vendorDir . '/cloverphp/nano/src/functions.php',
    'a80a00e91dfb988b39fee09aeaac3a1e' => $vendorDir . '/simple-swoole/simps/src/functions.php',
);
