<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Simps\\DB\\' => array($vendorDir . '/simple-swoole/db/src'),
    'Simps\\' => array($vendorDir . '/simple-swoole/simps/src'),
    'Server\\' => array($baseDir . '/servers'),
    'Module\\' => array($baseDir . '/modules'),
    'Model\\' => array($baseDir . '/models'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'Exception\\' => array($baseDir . '/exceptions'),
    'Clover\\Nano\\' => array($vendorDir . '/cloverphp/nano/src'),
    'App\\' => array($baseDir . '/apps'),
);
